# Generated by Django 3.2.4 on 2021-06-30 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20210630_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('number_of_bids', models.IntegerField()),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('bidding_increment', models.DecimalField(decimal_places=2, max_digits=4)),
                ('time_starting', models.DateTimeField()),
                ('time_ending', models.DateTimeField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
