# Generated by Django 3.2.4 on 2021-06-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='time_ending',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='time_starting',
            new_name='starting_time',
        ),
    ]
