# Generated by Django 3.2.4 on 2021-06-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210630_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='end_time',
            new_name='end_date_time',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='starting_time',
            new_name='start_date_time',
        ),
    ]
