# Generated by Django 3.2.4 on 2021-07-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bag_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
