# Generated by Django 3.2.4 on 2021-07-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210630_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='FA_icon_class',
            field=models.CharField(default='fas fa-exclamation', max_length=150),
        ),
    ]
