# Generated by Django 3.2.4 on 2021-07-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_fa_icon_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='FA_icon_class',
            new_name='fa_icon_class',
        ),
    ]
