# Generated by Django 3.2.4 on 2021-07-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_fa_icon_class_category_fa_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='username',
        ),
    ]
